# Generated by Django 3.2 on 2021-05-06 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('aisle', models.CharField(choices=[('Spices and Seasonings', 'Spices and Seasonings'), ('Produce', 'Produce'), ('Meat and Sausages', 'Meat and Sausages'), ('Poultry', 'Poultry'), ('Milk Eggs and Other Dairy', 'Milk Eggs and Other Dairy'), ('Seafood', 'Seafood'), ('Bakery and Bread', 'Bakery and Bread'), ('Pasta and Rice', 'Pasta and Rice'), ('Cheese', 'Cheese'), ('Oil Vinegar and Salad Dressing', 'Oil Vinegar and Salad Dressing'), ('Dried Fruits', 'Dried Fruits'), ('Nut butters Jams and Honey', 'Nut butters Jams and Honey'), ('Ethnic Foods', 'Ethnic Foods'), ('Tea and Coffee', 'Tea and Coffee'), ('Alcoholic Beverages', 'Alcoholic Beverages'), ('Canned and Jarred', 'Canned and Jarred'), ('Frozen', 'Frozen')], default='Spices and Seasonings', max_length=100)),
            ],
            options={
                'ordering': ['-aisle'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pantry', models.ManyToManyField(to='main_app.Ingredient')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Planned Meal Date')),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('R', 'Brunch'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1)),
                ('recipe_name', models.CharField(max_length=300)),
                ('recipe_url', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
