# Generated by Django 3.2 on 2021-04-29 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('unit', models.CharField(choices=[('gm', 'Grams'), ('cups', 'Cups'), ('items', 'Each'), ('oz', 'Ounces'), ('Tbsp', 'Tablespoons'), ('tsp', 'Teaspoons'), ('lbs', 'Pounds'), ('gallons', 'Gallon'), ('ml', 'Milliliters'), ('pint', 'Pint')], default='gm', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
