# Generated by Django 3.2 on 2021-05-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_meal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(verbose_name='Planned Meal Date/Time:'),
        ),
    ]
