# Generated by Django 3.2 on 2021-05-01 06:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_auto_20210501_0519'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foodie',
            new_name='Profile',
        ),
    ]
