# Generated by Django 3.2 on 2021-05-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_meal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(verbose_name='Planned Meal Date:'),
        ),
    ]
