# Generated by Django 3.2 on 2021-05-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_foodie_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='aisle',
            field=models.CharField(choices=[('Spices and Seasonings', 'Spices and Seasonings'), ('Pasta and Rice', 'Pasta and Rice'), ('Bakery/Bread', 'Bakery/Bread'), ('Produce', 'Produce'), ('Meat/Sausages', 'Meat/Sausages'), ('Poultry', 'Poultry'), ('Seafood', 'Seafood'), ('Cheese', 'Cheese'), ('Dried Fruits', 'Dried Fruits'), ('Nut butters, Jams, and Honey', 'Nut butters, Jams, and Honey'), ('Oil, Vinegar, Salad Dressing', 'Oil, Vinegar, Salad Dressing'), ('Condiments', 'Condiments'), ('Milk, Eggs, Other Dairy', 'Milk, Eggs, Other Dairy'), ('Ethnic Foods', 'Ethnic Foods'), ('Tea and Coffee', 'Tea and Coffee'), ('Refrigerated', 'Refrigerated'), ('Canned and Jarred', 'Canned and Jarred'), ('Frozen', 'Frozen'), ('Alcoholic Beverages', 'Alcoholic Beverages')], default='Spices and Seasonings', max_length=50),
        ),
    ]
