# Generated by Django 3.2 on 2021-05-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_foodie_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='recipe_name',
            field=models.CharField(default='python', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='recipe_url',
            field=models.CharField(default='http://www.python.org', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(verbose_name='Planned Meal Date'),
        ),
    ]
