# Generated by Django 3.2 on 2021-05-05 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_ingredient_aisle'),
        ('main_app', '0005_auto_20210504_2352'),
    ]

    operations = [
    ]
