# Generated by Django 3.2 on 2021-05-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_merge_20210505_0232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['aisle']},
        ),
    ]
