# Generated by Django 3.2 on 2021-05-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_ingredient_aisle'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
    ]
