# Generated by Django 3.2 on 2021-05-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_ingredient_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-aisle']},
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='color',
        ),
    ]
