# Generated by Django 3.2 on 2021-05-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20210505_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['aisle']},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='aisle',
            field=models.CharField(choices=[('Spices and Seasonings', 'Spices and Seasonings'), ('Pasta and Rice', 'Pasta and Rice'), ('Bakery and Bread', 'Bakery and Bread'), ('Produce', 'Produce'), ('Meat and Sausages', 'Meat and Sausages'), ('Poultry', 'Poultry'), ('Seafood', 'Seafood'), ('Cheese', 'Cheese'), ('Dried Fruits', 'Dried Fruits'), ('Nut butters, Jams, and Honey', 'Nut butters, Jams, and Honey'), ('Oil Vinegar and Salad Dressing', 'Oil Vinegar and Salad Dressing'), ('Milk Eggs and Other Dairy', 'Milk Eggs and Other Dairy'), ('Ethnic Foods', 'Ethnic Foods'), ('Tea and Coffee', 'Tea and Coffee'), ('Canned and Jarred', 'Canned and Jarred'), ('Frozen', 'Frozen'), ('Alcoholic Beverages', 'Alcoholic Beverages')], default='Spices and Seasonings', max_length=50),
        ),
    ]
