# Generated by Django 3.2 on 2021-05-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20210505_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['-aisle']},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='aisle',
            field=models.CharField(choices=[('Spices and Seasonings', 'Spices and Seasonings'), ('Produce', 'Produce'), ('Meat and Sausages', 'Meat and Sausages'), ('Poultry', 'Poultry'), ('Milk Eggs and Other Dairy', 'Milk Eggs and Other Dairy'), ('Seafood', 'Seafood'), ('Bakery and Bread', 'Bakery and Bread'), ('Pasta and Rice', 'Pasta and Rice'), ('Cheese', 'Cheese'), ('Oil Vinegar and Salad Dressing', 'Oil Vinegar and Salad Dressing'), ('Dried Fruits', 'Dried Fruits'), ('Nut butters Jams and Honey', 'Nut butters Jams and Honey'), ('Ethnic Foods', 'Ethnic Foods'), ('Tea and Coffee', 'Tea and Coffee'), ('Alcoholic Beverages', 'Alcoholic Beverages'), ('Canned and Jarred', 'Canned and Jarred'), ('Frozen', 'Frozen')], default='Spices and Seasonings', max_length=100),
        ),
    ]
